# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod.version=1.3.0
mod.group=net.katch0420
mod.id=macebot
mod.name=MaceBot

# Global dependencies
deps.fabric_loader=0.17.0

publish.modrinth=# Modrinth mod slug
publish.curseforge=# Curseforge numeric mod ID